### ISSUE TITLE
User Profile Set-up Flow

### ISSUE THREAD

**Issue by Bricktheworld** [CS-130-Organization/CredibleCupid#41]
## User Story
As a **new user**, I would like **to sign up and set up my profile with a bio** so that **I can personalize my profile and make it visible to other users**.

## Detailed Description
Create a multi-step sign-up flow that includes a profile setup stage. After completing the basic sign-up (e.g., email, password), the user will be directed to a bio setup page to add details about themselves. The profile setup page will guide the user through filling out key fields (e.g., bio, interests, profile picture) to create a complete and engaging profile. Each step should be simple and provide guidance on what kind of information to include.

## Acceptance Criteria
- [x] Given **a user starts the sign-up process**, then **they are prompted to enter their email, password, and any other required credentials**.
- [x] Given **the user completes sign-up**, then **they are directed to a profile setup flow to add details such as bio, gender, birthday and profile picture**.
- [x] Given **the user reaches the bio setup page**, then **they see fields for bio, interests, and a prompt to upload a profile picture**.
- [x] Given **the user fills out the bio setup form and submits**, then **the profile is saved and the user is notified of successful profile creation**.

**Comment by clairezhang03** [comment]
Implemented in PR#44
