### ISSUE TITLE
User Sign-Up with Email and Password

### ISSUE THREAD

**Issue by Bricktheworld** [CS-130-Organization/CredibleCupid#42]
## User Story
As a **new user**, I would like **to sign up using my email and password** so that **I can create an account and access the application**.

## Detailed Description
Implement a sign-up feature that allows new users to register by providing an email and password. The form should include basic validation (e.g., valid email format, password strength) and display appropriate error messages for invalid input. After successful sign-up, the user should receive a confirmation or welcome message and be redirected to the next step (e.g., profile setup).

## Acceptance Criteria
- [x] Given **a user accesses the sign-up page**, then **they see fields for entering an email and password**.
- [x] Given **the user enters an invalid email**, then **an error message appears indicating the email format is incorrect**.
- [x] Given **the user enters a weak password**, then **an error message appears suggesting stronger password criteria**.
- [x] Given **the user enters a valid email and password**, then **their account is created, and they are redirected to the next step or shown a welcome message**.
- [x] Given **a new account is created**, then **the user’s email and password are securely stored in the database**.

**Comment by clairezhang03** [comment]
Implemented with PR #44
